# Generated by Django 6.0 on 2025-12-09 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CinemaHall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название зала')),
                ('capacity', models.PositiveIntegerField(verbose_name='Вместимость')),
                ('description', models.TextField(blank=True, verbose_name='Описание зала')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Кинозал',
                'verbose_name_plural': 'Кинозалы',
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название фильма')),
                ('description', models.TextField(verbose_name='Описание')),
                ('duration_minutes', models.PositiveIntegerField(verbose_name='Продолжительность (мин)')),
                ('release_year', models.PositiveIntegerField(verbose_name='Год выпуска')),
                ('genre', models.CharField(max_length=100, verbose_name='Жанр')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Screening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Время начала')),
                ('end_time', models.DateTimeField(verbose_name='Время окончания')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена билета')),
                ('available_seats', models.PositiveIntegerField(verbose_name='Доступные места')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.film', verbose_name='Фильм')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.cinemahall', verbose_name='Зал')),
            ],
            options={
                'verbose_name': 'Сеанс',
                'verbose_name_plural': 'Сеансы',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='Email клиента')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Телефон клиента')),
                ('seats', models.PositiveIntegerField(verbose_name='Количество мест')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая стоимость')),
                ('status', models.CharField(choices=[('confirmed', 'Подтверждено'), ('cancelled', 'Отменено'), ('pending', 'В ожидании')], default='pending', max_length=20)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('booking_reference', models.CharField(max_length=10, unique=True, verbose_name='Номер брони')),
                ('screening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.screening', verbose_name='Сеанс')),
            ],
            options={
                'verbose_name': 'Бронь',
                'verbose_name_plural': 'Брони',
                'ordering': ['-booking_date'],
            },
        ),
    ]
